apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polkadot-otv-backend
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: polkadot
  project: 1kv-backend
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  source:
    repoURL: https://w3f.github.io/helm-charts/
    chart: otv-backend
    targetRevision: v2.8.39
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              tag: "v2.8.39"
            environment: {{ .Values.environment }}
            dataPath: "/data"
            backendPort: 3300
            domain: {{ .Values.polkadot.be.domain | quote }}

            resources:
              limits:
                cpu: 3500m
                memory: 9Gi
              requests:
                cpu: 700m
                memory: 3Gi

            secret: |
              {{ .Values.polkadot.be.secret }}

            config: |
              {
                "global": {
                  "dryRun": false,
                  "networkPrefix": 0,
                  "test": false,
                  "retroactive": false,
                  "historicalNominations": false,
                  "apiEndpoints":  {{ .Values.polkadot.be.apiEndpoints | toJson  }}
                },
                "constraints": {
                  "skipConnectionTime": false,
                  "skipIdentity": false,
                  "skipStakedDestination": true,
                  "skipClientUpgrade": false,
                  "forceClientVersion": "v0.9.39",
                  "skipUnclaimed": true,
                  "minSelfStake": 50000000000000,
                  "commission": 50000000,
                  "unclaimedEraThreshold": 1
                },
                "cron": {
                  "monitor": "0 */15 * * * *"
                },
                "db": {
                  "mongo": {
                      "uri": {{ .Values.polkadot.db.uri | quote}}
                  }
                },
                "matrix": {
                  "enabled": true,
                  "baseUrl": "https://matrix.org",
                  "room": {{ .Values.polkadot.be.matrix.room | quote}},
                  "userId": {{ .Values.polkadot.be.matrix.userId | quote}}
                },
                "proxy": {
                    "timeDelayBlocks": "10850",
                    "blacklistedAnnouncements": []
                },
                {{- $v := $.Files.Get "scores.yaml" | fromYaml }}
                "score": {{ $v.polkadot | toJson }},
                "scorekeeper": {
                  {{- $v := $.Files.Get "candidatesPolkadot.yaml" | fromYaml }}
                  "candidates": {{ $v.candidates | toJson }},              
                  "forceRound": false,
                  "nominating": true
                },
                "server": {
                  "port": 3300,
                  "enable": true
                },
                "telemetry": {
                  "enable": true,
                  "chains": [
                      "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3"
                  ],
                  "blacklistedProviders": [
                    "Hetzner Online GmbH",
                    "Contabo Inc.",
                    "Contabo GmbH"
                  ],
                  "host": "wss://telemetry-backend.w3f.community/feed"
                },
                "subscan": {
                    "baseV1Url": "https://polkadot.api.subscan.io/api/scan",
                    "baseV2Url": "https://polkadot.api.subscan.io/api/v2/scan"
                }
              }
