export * from "./ReleaseMonitorJob";
export * from "./ConstraintsJob";
export * from "./EraStatsJob";
export * from "./EraPointsJob";
export * from "./ValidatorPrefJob";
export * from "./SessionKeyJob";
export * from "./InclusionJob";
export * from "./ActiveValidatorJob";
export * from "./LocationStatsJob";
export * from "./CouncilJob";
export * from "./DemocracyJob";
export * from "./NominatorJob";
export * from "./DelegationJob";
export * from "./BlockDataJob";
export * from "./UnclaimedErasJob";

export const ACTIVE_VALIDATOR_JOB = "activeValidatorJob";
export const COUNCIL_JOB = "councilJob";
export const DELEGATION_JOB = "delegationJob";
export const DEMOCRACY_JOB = "democracyJob";
export const ERA_POINTS_JOB = "eraPointsJob";
export const ERA_STATS_JOB = "eraStatsJob";
export const INCLUSION_JOB = "inclusionJob";
export const NOMINATOR_JOB = "nominatorJob";
export const SESSION_KEY_JOB = "sessionKeyJob";
export const VALIDATOR_PREF_JOB = "validatorPrefJob";
export const VALIDITY_JOB = "validityJob";
export const SCORE_JOB = "scoreJob";
export const BLOCK_JOB = "blockJob";

export const UNCLAIMED_ERAS_JOB = "unclaimedErasJob";
