apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "otv-backend.core-release-name" . }}
  labels:
    app: {{ include "otv-backend.core-release-name" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: {{ include "otv-backend.core-release-name" . }}
  serviceName: {{ include "otv-backend.core-release-name" . }}
  template:
    metadata:
      labels:
        app: {{ include "otv-backend.core-release-name" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/core/configmap.yaml") . | sha256sum }}  
        checksum/secret: {{ include (print $.Template.BasePath "/core/secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ include "otv-backend.core-release-name" . }}
        image: {{ .Values.core.image.repo }}:{{ .Values.core.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: {{ .Values.port }}
        # livenessProbe:
        #   httpGet:
        #     path: /healthcheck
        #     port: {{ .Values.port }}
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 20
        volumeMounts:
        - name: data
          mountPath: /data
        - name: secret-config
          mountPath: /code/packages/core/config/secret.json
          subPath: secret.json
          readOnly: true
        - name: main-config
          mountPath: /code/packages/core/config/main.json
          subPath: main.json
          readOnly: true
      {{- if ne .Values.environment "ci" }}
        resources:
{{ toYaml .Values.core.resources | indent 10 }}
      {{- end }}
      {{- if eq .Values.environment "ci" }}
        env:
        - name: CI
          value: "true"
      {{- end }}
      volumes:
      - name: secret-config
        secret:
          secretName: {{ include "otv-backend.core-release-name" . }}
      - name: main-config
        configMap:
          name: {{ include "otv-backend.core-release-name" . }}
      {{ if eq .Values.environment "ci" }}
      - name: data
        emptyDir: {}
      {{ else }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.core.storageSize }}
      {{ end }}
