apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kusama-otv-backend-staging
  namespace: argocd
# finalizers:
# - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kusama-1kv-staging
  project: 1kv-backend-staging
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true 
  source:
    repoURL: https://w3f.github.io/helm-charts/
    chart: otv-backend
    targetRevision: v3.0.12
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            # image:
            #   tag: "latest"
            environment: {{ .Values.environment }}
            dataPath: "/data"
            backendPort: 3300
            ingress:
              domain: {{ .Values.kusama.be.domain | quote }}

            resources:
              {{- toYaml .Values.kusama.be.resources | nindent 14 }}

            storageSize: {{ .Values.kusama.be.storage }}

            secret: |
              {{ .Values.kusama.be.secret }}

            config: |
              {
                "global": {
                  "dryRun": false,
                  "networkPrefix": 2,
                  "apiEndpoints": [
                    "wss://kusama-rpc.polkadot.io"
                  ],
                  "candidatesUrl": "https://raw.githubusercontent.com/w3f/1k-validators-be/master/candidates/kusama.json"
                },
                "constraints": {
                  "skipConnectionTime": true,
                  "skipIdentity": false,
                  "skipClientUpgrade": false,
                  "forceClientVersion": "v0.9.39",
                  "skipUnclaimed": true,
                  "minSelfStake": 10000000000000,
                  "commission": 150000000,
                  "unclaimedEraThreshold": 4
                },
                "cron": {
                  "monitor": "0 */15 * * * *"
                },
                "db": {
                  "mongo": {
                      "uri": {{ .Values.kusama.db.uri | quote }}
                  }
                },
                "matrix": {
                  "enabled": true,
                  "baseUrl": "https://matrix.web3.foundation",
                  "room": {{ .Values.kusama.be.matrix.room | quote}},
                  "userId": {{ .Values.kusama.be.matrix.userId | quote}}
                },
                "proxy": {
                    "timeDelayBlocks": "10850",
                    "blacklistedAnnouncements": []
                },
                "score": {{ range .Files.Lines "config/kusama-score.json" }}
                  {{ . }}{{ end }},
                "scorekeeper": {
                  "candidates": null,
                  "forceRound": false,
                  "nominating": {{ .Values.kusama.be.nominating }}
                },
                "server": {
                  "port": 3300,
                  "enable": true
                },
                "telemetry": {
                  "enable": true,
                  "chains": [
                      "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe"
                  ],
                  "blacklistedProviders": [
                    "Hetzner Online GmbH",
                    "Contabo Inc.",
                    "Contabo GmbH"
                  ],
                  "host": "wss://telemetry-backend.w3f.community/feed"
                }
              }
